//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public decimal TransactionId { get; set; }
        public decimal EnrollId { get; set; }
        public int Amount { get; set; }
        public string Mode { get; set; }
    
        public virtual Enroll Enroll { get; set; }
    }
}
